services:
  postgres:
    image: postgres:16
    container_name: nodagent-postgres

    env_file:
      - .env

    ports:
      - "15432:5432"

    volumes:
      - nodagent_postgres_data:/var/lib/postgresql/data

    restart: unless-stopped


volumes:
  nodagent_postgres_data:
    name: nodagent_postgres_data